// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeStream.VisualStudio.Vsix.x64
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeStreamPackageString = "5498f07e-2ca1-4d3b-bcfb-5e8a8a082eed";
        public static Guid guidCodeStreamPackage = new Guid(guidCodeStreamPackageString);

        public const string guidWebViewPackageCmdSetString = "8f66deb0-240b-4137-8550-723344e49722";
        public static Guid guidWebViewPackageCmdSet = new Guid(guidWebViewPackageCmdSetString);

        public const string guidHtmlCtxMenuString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid guidHtmlCtxMenu = new Guid(guidHtmlCtxMenuString);

        public const string guidWebViewPackageCodeWindowContextMenuCmdSetString = "0f33235e-3a5c-42bc-b519-d888652f972c";
        public static Guid guidWebViewPackageCodeWindowContextMenuCmdSet = new Guid(guidWebViewPackageCodeWindowContextMenuCmdSetString);

        public const string guidWebViewPackageShortcutCmdSetString = "a72bbf5d-23d2-4a8a-939e-12c4651dd341";
        public static Guid guidWebViewPackageShortcutCmdSet = new Guid(guidWebViewPackageShortcutCmdSetString);

        public const string guidImagesString = "f2c8ef6d-3257-4e0a-8ae0-ef6298dd22c5";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImagesCommandsString = "c438d577-2a1c-4cee-8b33-e056c2281595";
        public static Guid guidImagesCommands = new Guid(guidImagesCommandsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int ToolbarGroup100 = 0x1060;
        public const int CodeStreamMenuController100 = 0x9001;
        public const int CodeStreamMenuController200 = 0x9901;
        public const int CodeStreamMenuControllerGroup100 = 0x9003;
        public const int CodeStreamMenuControllerGroup200 = 0x9004;
        public const int WebViewToggleCommandId = 0x0100;
        public const int AuthenticationCommandId = 0x0200;
        public const int UserCommandId = 0x0300;
        public const int WebViewReloadCommandId = 0x0400;
        public const int WebViewDevToolsCommandId = 0x0600;
        public const int IDM_HTMLCTXMENU = 0x0001;
        public const int CodeWindowContextSubMenuGroup = 0x9000;
        public const int CodeWindowContextCommandGroup = 0x9001;
        public const int CodeWindowContextSubMenu = 0x9200;
        public const int CodeStreamEditorCommands = 0x1023;
        public const int AddCodemarkCommentCommandId = 0x0400;
        public const int AddCodemarkIssueCommandId = 0x0401;
        public const int AddCodemarkPermalinkCommandId = 0x0403;
        public const int AddCodemarkPermalinkInstantCommandId = 0x0413;
        public const int RequestCodeReviewCommandId = 0x0433;
        public const int CodeStreamShortcutCommands = 0x1023;
        public const int StartWorkCommandId = 0x0423;
        public const int logo = 0x0001;
        public const int auth = 0x0002;
        public const int user = 0x0003;
        public const int empty4 = 0x0004;
        public const int empty5 = 0x0005;
        public const int empty6 = 0x0006;
        public const int comment = 0x0001;
        public const int issue = 0x0002;
        public const int bookmark = 0x0003;
        public const int permalink = 0x0004;
        public const int instantPermalink = 0x0005;
        public const int review = 0x0006;
    }
}
