#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Skip if running in CI
[ -n "$TEAMCITY_VERSION" ] && exit 0

AGENT_FILES=$(git diff --cached --name-only --diff-filter=ACM "shared/agent/*")
UI_FILES=$(git diff --cached --name-only --diff-filter=ACM "shared/ui/*")
UTIL_FILES=$(git diff --cached --name-only --diff-filter=ACM "shared/util/*")

if [[ -n "$AGENT_FILES" ]] || [[ -n "$UTIL_FILES" ]]; then
    echo "Compile / Lint Agent Files"
    pushd shared/agent
    npm run verify:compile
    npx lint-staged
    popd
fi

if [[ -n "$UI_FILES" ]] || [[ -n "$UTIL_FILES" ]]; then
    echo "Compile / Lint UI Files"
    pushd shared/ui
    npm run verify:compile
    npx lint-staged
    popd
fi